name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: FE-UniBazaar/package-lock.json  # Correct path for cache

    - name: Install Dependencies
      run: npm ci
      working-directory: FE-UniBazaar  # Set correct working directory

    - name: Build Application
      run: npm run build --if-present
      working-directory: FE-UniBazaar  # Set correct working directory

    - name: Run Tests
      run: npm test
      working-directory: FE-UniBazaar  # Set correct working directory
