name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'FE-UniBazaar/**'
      
  pull_request:
    branches: [ "main" ]
    paths:
      - 'FE-UniBazaar/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: FE-UniBazaar/package-lock.json  # Ensures correct caching
    
    - name: Install dependencies
      run: npm ci
      working-directory: FE-UniBazaar  # Runs npm commands inside FE-UniBazaar

    - name: Build application
      run: npm run build --if-present
      working-directory: FE-UniBazaar

    - name: Run tests
      run: npm test
      working-directory: FE-UniBazaar
